server:
  port: 8888

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: msorder-route
          uri: lb://msorder
          predicates:
            - Path=/orders/**

        - id: msorder-search-route
          uri: lb://msorder
          predicates:
            - Path=/orders/search

        - id: msproduct-route
          uri: lb://msproduct
          predicates:
            - Path=/products/**

        - id: msproduct-search-route
          uri: lb://msproduct
          predicates:
            - Path=/products/search

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true



